import { promises as fs } from "node:fs";
import path from "node:path";

import { getProductBySlug } from "@/data/products";

const PRODUCTS_DIR = path.join(process.cwd(), "src", "data", "products");

const SLUG_BY_PRODUCT_ID: Record<string, string> = {
  web: "web",
  core: "core",
  scrapy: "scrapy",
  extractSummit: "extract-summit",
};

async function readGeneratedCss(productId: string): Promise<string | null> {
  const slug = SLUG_BY_PRODUCT_ID[productId];
  if (!slug) return null;
  try {
    return await fs.readFile(
      path.join(PRODUCTS_DIR, slug, "dist", "tokens.css"),
      "utf-8",
    );
  } catch {
    return null;
  }
}

export default async function ProductScopeLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ productId: string }>;
}) {
  const { productId: slug } = await params;
  const product = getProductBySlug(slug);
  const css = product ? await readGeneratedCss(product.id) : null;

  return (
    <>
      {/* Inject the codegen-generated tokens.css for this product so its
          CSS variables (`--<slug>-*`) are queryable in DevTools and usable by
          downstream components. The file is regenerated by predev/prebuild,
          so navigating between products always reflects the latest
          foundations.ts. */}
      {css ? (
        <style
          data-product={product?.slug}
          dangerouslySetInnerHTML={{ __html: css }}
        />
      ) : null}
      {children}
    </>
  );
}
