import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Zyte brand fonts (copy font files from zyte.com project into public/fonts)
// Yellix: main brand sans
export const yellix = localFont({
  src: [
    {
      path: "../public/fonts/Yellix-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Yellix-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Yellix-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Yellix-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-zyte-sans",
  display: "swap",
});

// Space Mono: secondary mono font used across zyte.com
export const spaceMono = localFont({
  src: [
    {
      path: "../public/fonts/SpaceMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SpaceMono-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-zyte-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${yellix.variable} ${spaceMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
